[package]
name = "filmstamp"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.29"
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.39", features = ["derive"] }
image = "0.25.6"
imageproc = "0.25.0"
kamadak-exif = "0.6.1"
